#include <stdio.h>
#include <string.h>

#define TAILLE 256

typedef struct {
    char mot[20];
    unsigned char octet;
} Association;

int main() {
    // Tableau d'association entre mots et octets
    Association tableau[TAILLE] = {
        {"is", 0x00},
        {"was", 0x01},
        {"are", 0x02},
        {"be", 0x03},
        {"have", 0x04},
        {"had", 0x05},
        {"were", 0x06},
        {"can", 0x07},
        {"said", 0x08},
        {"use", 0x09},
        {"do", 0x0A},
        {"will", 0x0B},
        {"would", 0x0C},
        {"make", 0x0D},
        {"like", 0x0E},
        {"has", 0x0F},
        {"look", 0x10},
        {"write", 0x11},
        {"go", 0x12},
        {"see", 0x13},
        {"could", 0x14},
        {"been", 0x15},
        {"call", 0x16},
        {"am", 0x17},
        {"find", 0x18},
        {"did", 0x19},
        {"get", 0x1A},
        {"come", 0x1B},
        {"made", 0x1C},
        {"may", 0x1D},
        {"take", 0x1E},
        {"know", 0x1F},
        {"live", 0x20},
        {"give", 0x21},
        {"think", 0x22},
        {"say", 0x23},
        {"help", 0x24},
        {"tell", 0x25},
        {"follow", 0x26},
        {"came", 0x27},
        {"want", 0x28},
        {"show", 0x29},
        {"set", 0x2A},
        {"put", 0x2B},
        {"does", 0x2C},
        {"must", 0x2D},
        {"ask", 0x2E},
        {"went", 0x2F},
        {"read", 0x30},
        {"need", 0x31},
        {"move", 0x32},
        {"try", 0x33},
        {"change", 0x34},
        {"play", 0x35},
        {"spell", 0x36},
        {"found", 0x37},
        {"study", 0x38},
        {"learn", 0x39},
        {"should", 0x3A},
        {"add", 0x3B},
        {"keep", 0x3C},
        {"start", 0x3D},
        {"thought", 0x3E},
        {"saw", 0x3F},
        {"turn", 0x40},
        {"might", 0x41},
        {"close", 0x42},
        {"seem", 0x43},
        {"open", 0x44},
        {"begin", 0x45},
        {"got", 0x46},
        {"run", 0x47},
        {"walk", 0x48},
        {"began", 0x49},
        {"grow", 0x4A},
        {"took", 0x4B},
        {"carry", 0x4C},
        {"hear", 0x4D},
        {"stop", 0x4E},
        {"miss", 0x4F},
        {"eat", 0x50},
        {"watch", 0x51},
        {"let", 0x52},
        {"cut", 0x53},
        {"talk", 0x54},
        {"being", 0x55},
        {"leave", 0x56},
        {"word", 0x57},
        {"time", 0x58},
        {"number", 0x59},
        {"way", 0x5A},
        {"people", 0x5B},
        {"water", 0x5C},
        {"day", 0x5D},
        {"part", 0x5E},
        {"sound", 0x5F},
        {"work", 0x60},
        {"place", 0x61},
        {"year", 0x62},
        {"back", 0x63},
        {"thing", 0x64},
        {"name", 0x65},
        {"sentence", 0x66},
        {"man", 0x67},
        {"line", 0x68},
        {"boy", 0x69},
        {"farm", 0x6A},
        {"end", 0x6B},
        {"men", 0x6C},
        {"land", 0x6D},
        {"home", 0x6E},
        {"hand", 0x6F},
        {"picture", 0x70},
        {"air", 0x71},
        {"animal", 0x72},
        {"house", 0x73},
        {"page", 0x74},
        {"letter", 0x75},
        {"point", 0x76},
        {"mother", 0x77},
        {"answer", 0x78},
        {"America", 0x79},
        {"world", 0x7A},
        {"food", 0x7B},
        {"country", 0x7C},
        {"plant", 0x7D},
        {"school", 0x7E},
        {"father", 0x7F},
        {"tree", 0x80},
        {"city", 0x81},
        {"earth", 0x82},
        {"eye", 0x83},
        {"head", 0x84},
        {"story", 0x85},
        {"example", 0x86},
        {"life", 0x87},
        {"paper", 0x88},
        {"group", 0x89},
        {"children", 0x8A},
        {"side", 0x8B},
        {"feet", 0x8C},
        {"car", 0x8D},
        {"mile", 0x8E},
        {"night", 0x8F},
        {"sea", 0x90},
        {"river", 0x91},
        {"state", 0x92},
        {"book", 0x93},
        {"idea", 0x94},
        {"face", 0x95},
        {"Indian", 0x96},
        {"girl", 0x97},
        {"mountain", 0x98},
        {"list", 0x99},
        {"song", 0x9A},
        {"family", 0x9B},
        {"he", 0x9C},
        {"a", 0x9D},
        {"one", 0x9E},
        {"all", 0x9F},
        {"an", 0xa0},
        {"each", 0xa1},
        {"other", 0xa2},
        {"many", 0xa3},
        {"some", 0xa4},
        {"two", 0xa5},
        {"more", 0xa6},
        {"long", 0xa7},
        {"new", 0xa8},
        {"little", 0xa9},
        {"most", 0xaA},
        {"good", 0xaB},
        {"great", 0xaC},
        {"right", 0xaD},
        {"mean", 0xaE},
        {"old", 0xaF},
        {"any", 0xb0},
        {"same", 0xb1},
        {"three", 0xb2},
        {"small", 0xb3},
        {"another", 0xb4},
        {"large", 0xb5},
        {"big", 0xb6},
        {"even", 0xb7},
        {"such", 0xb8},
        {"different", 0xb9},
        {"kind", 0xbA},
        {"still", 0xbB},
        {"high", 0xbC},
        {"every", 0xbD},
        {"own", 0xbE},
        {"light", 0xbF},
        {"left", 0xc0},
        {"few", 0xc1},
        {"next", 0xc2},
        {"hard", 0xc3},
        {"both", 0xc4},
        {"important", 0xc5},
        {"white", 0xc6},
        {"four", 0xc7},
        {"second", 0xc8},
        {"enough", 0xc9},
        {"above", 0xcA},
        {"young", 0xcB},
        {"not", 0xcC},
        {"when", 0xcD},
        {"there", 0xcE},
        {"how", 0xcF},
        {"up", 0xD0},
        {"out", 0xD1},
        {"then", 0xD2},
        {"so", 0xD3},
        {"no", 0xD4},
        {"first", 0xD5},
        {"now", 0xD6},
        {"only", 0xD7},
        {"very", 0xD8},
        {"just", 0xD9},
        {"where", 0xDA},
        {"much", 0xDB},
        {"before", 0xDC},
        {"too", 0xDD},
        {"also", 0xDE},
        {"around", 0xDF},
        {"well", 0xE0},
        {"here", 0xE1},
        {"why", 0xE2},
        {"again", 0xE3},
        {"off", 0xE4},
        {"away", 0xE5},
        {"near", 0xE6},
        {"below", 0xE7},
        {"last", 0xE8},
        {"never", 0xE9},
        {"always", 0xEA},
        {"together", 0xEB},
        {"often", 0xEC},
        {"once", 0xED},
        {"later", 0xEE},
        {"far", 0xEF},
        {"really", 0xf0},
        {"almost", 0xf1},
        {"sometimes", 0xf2},
        {"soon", 0xf3},
        {"of", 0xf4},
        {"to", 0xf5},
        {"in", 0xf6},
        {"for", 0xf7},
        {"on", 0xf8},
        {"with", 0xf9},
        {"at", 0xfA},
        {"from", 0xfB},
        {"by", 0xfC},
        {"about", 0xfD},
        {"into", 0xfE},
        {"down", 0xfF},
    };

    // Calcul de la taille réelle du tableau
    int assoc_size = sizeof(tableau) / sizeof(tableau[0]);

    // Message contenant les mots à associer
    const char *message = "raisin banane orange fraise pomme a";
    unsigned char result[TAILLE] = {0};
    int result_index = 0;

    // Dupliquer la chaîne pour la tokeniser
    char buffer[100];
    strcpy(buffer, message);

    // Découper la chaîne en mots
    char *token = strtok(buffer, " ");
    while (token != NULL) {
        for (int i = 0; i < assoc_size; i++) {
            if (strcmp(token, tableau[i].mot) == 0) {
                result[result_index++] = tableau[i].octet;
                break;
            }
        }
        token = strtok(NULL, " ");
    }

    result[result_index] = '\0';

    // ✅ Affichage du résultat sous forme hexadécimale
    printf("msg[] = \"");
    for (int i = 0; i < result_index; i++) {
        printf("\\x%02X", result[i]);
    }
    printf("\"\n");

    return 0;
}
