name: Deploy setup.sh via FTP

on:
  push:
    branches:
      - main
    paths:
      - "setup.sh"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload setup.sh over FTP
        env:
          FTP_SCHEME: ${{ secrets.FTP_SCHEME }}   # "ftp" (ou "ftps" si dispo)
          FTP_HOST:   ${{ secrets.FTP_HOST }}     # ex: ftp.exemple.com
          FTP_DIR:    ${{ secrets.FTP_DIR }}      # ex: public_html/scripts
          FTP_USER:   ${{ secrets.FTP_USER }}
          FTP_PASS:   ${{ secrets.FTP_PASS }}
        run: |
          set -euo pipefail
          : "${FTP_SCHEME:=ftp}"  # défaut: ftp
          # Crée les dossiers distants si besoin et pousse le fichier
          curl --fail --silent --show-error \
               --ftp-create-dirs \
               -T setup.sh \
               "${FTP_SCHEME}://${FTP_HOST}/${FTP_DIR}/" \
               --user "${FTP_USER}:${FTP_PASS}"
          echo "Deployed setup.sh to ${FTP_SCHEME}://${FTP_HOST}/${FTP_DIR}/"
