name: Normalize Line Endings

on:
  push:
    branches:
      - main

jobs:
  normalize-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix

      - name: Convert .sh files to Unix format
        run: |
          find . \
            -type f \
            \( -name "*.sh" -o -name "*.py" -o -name "*.json" -o -name "*.yml" -o -name "*.yaml" -o -name "*.conf" -o -name "*.env" -o -name "*.txt" -o -name "*.md" \) \
            -exec dos2unix {} +

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[auto] normalize line endings in .sh files" || exit 0
          git push