name: Normalize Line Endings

on:
  push:
    branches:
      - main

jobs:
  normalize-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix

      - name: Convert text/code files to Unix format
        run: |
          extensions=(
            "*.sh"
            "*.py"
            "*.json"
            "*.yml"
            "*.yaml"
            "*.conf"
            "*.env"
            "*.txt"
            "*.md"
          )

          for ext in "${extensions[@]}"; do
            find . -type f -name "$ext" -exec dos2unix {} +
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[auto] normalize line endings" || exit 0
          git push