name: Oneliner Install Check

on:
  workflow_run:
    workflows: ["Deploy setup.sh via FTP"]
    types:
      - completed

jobs:
  followup:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Update apt and install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl git

    - name: Test oneliner
      run: |
        set -euo pipefail
        curl -fsSL https://furdz.kyrd0x.net/install | sudo bash
        echo "Oneliner installation succeeded"