name: Test Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update apt and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64 python3-yaml
        chmod +x build.sh

    - name: Run default build
      run: |
        output=$(./build.sh)
        echo "$output"

        if ! echo "$output" | grep -q "Build completed"; then
          exit 1
        fi

    - name: Run alternative build
      run: |
        output=$(./build.sh --small)
        echo "$output"

        if ! echo "$output" | grep -q "Build completed"; then
          exit 1
        fi