name: Test Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update apt and install dependencies
      run: |
        chmod +x ./scripts/setup.sh
        sudo ./scripts/setup.sh

    - name: Run default build
      run: |
        output=$(./build.py --debug)
        echo "$output"

        if ! echo "$output" | grep -q "Build completed"; then
          exit 1
        fi

    - name: Run alternative build
      run: |
        output=$(./build.py --debug --small)
        echo "$output"

        if ! echo "$output" | grep -q "Build completed"; then
          exit 1
        fi